version: '3.7'

services: 
    autocomplete_suggestions:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: autocomplete_suggestions
        expose:
            - '3000'
        ports: 
            - '3000:3000'
        environment: 
            CONNECTION_STRING: "${CONNECTION_STRING}"
        command: yarn start